### ISSUE TITLE
RFE Provide a RPM package for itself

### ISSUE THREAD

**Issue by e-minguez** [javierpena/galaxy-collection-to-rpm#2]
It would be nice to have the script packaged and available somewhere (copr?) so you can install it with yum/dnf.

**Comment by javierpena** [comment]
Hm, good idea. Originally I planned this to be a simple script, but I see the value in getting it packaged. I'll work on that.

**Comment by e-minguez** [comment]
I followed this guide https://hobo.house/2017/09/03/automate-rpm-builds-from-git-sources-using-copr/ and I have some packages built automatically for the tools that are not packaged in Fedora/CentOS/RHEL here https://github.com/e-minguez/rpms I think it is really helpful just in case you want to do the same :)
